version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
    volumes:
      - ./logs:/app/logs
      - ./src:/app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"    
    volumes:
      - mongodb_data:/data/db
      # - ./storage:/data/db

volumes:
  mongodb_data:
